[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[build-dependencies]
candid = "0.10"

[dependencies]
candid = "0.10.8"
dotenv = "0.15.0"
ic-cdk = "0.14.0"
serde = "1.0.203"
serde_bytes = "0.11.14"
petgraph = "0.6.5"
serde_json = "1.0.117"
