name: Code Quality

on:
  workflow_call:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure Script Permissions
        run: find ./scripts -type f -name "*.sh" -exec chmod +x {} \;

      - name: Verify Script Permissions
        run: ls -l ./scripts/**/*.sh

      - name: Setup DFX
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "0.26.0"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Enable Corepack
        run: corepack enable

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.5
          run_install: false

      - name: Configure environment
        run: |
          echo "$HOME/.local/share/dfx/bin" >> $GITHUB_PATH
          dfx cache install

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.STORE_PATH }}
            ~/.cache/dfx
            ~/.cargo
            target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock', '**/pnpm-lock.yaml', 'dfx.json') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Full Build Process
        run: ./scripts/build.sh

      - name: Quality Assurance
        run: ./scripts/check.sh
