name: Code Quality

on:
  workflow_call:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'

      - name: Setup DFX
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "auto"

      - name: Setup Rust target
        run: rustup target add wasm32-unknown-unknown

      - name: Set build script permissions
        run: |
          chmod +x ./scripts/*.sh
          chmod +x ./scripts/**/*.sh

      - name: Setup DFX identity and start DFX
        run: |
          dfx identity new github-ci --disable-encryption || true
          dfx identity use github-ci
          ./scripts/deploy.sh

      - name: Format
        working-directory: ./src/pt_frontend
        run: npm run format:write

      - name: TypeCheck
        working-directory: ./src/pt_frontend
        run: npm run typecheck

      - name: Lint
        working-directory: ./src/pt_frontend
        run: npm run lint
