name: Code Quality

on:
  workflow_call:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure Script Permissions
        run: find ./scripts -type f -name "*.sh" -exec chmod +x {} \;

      - name: Verify Script Permissions
        run: ls -l ./scripts/**/*.sh

      - name: Setup DFX
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "0.24.3"

      - name: Configure environment
        run: |
          echo "$HOME/.local/share/dfx/bin" >> $GITHUB_PATH
          dfx cache install

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/dfx
            ~/.cargo
            target
            src/pt_frontend/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock', '**/package-lock.json', 'dfx.json') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Full Build Process
        run: ./scripts/build.sh

      - name: Quality Assurance
        run: ./scripts/check.sh
