name: Code Quality

on:
  workflow_call:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'

      - name: Setup DFX
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "auto"

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
          target: wasm32-unknown-unknown

      - name: Set build script permissions
        run: |
          chmod +x ./scripts/*.sh
          chmod +x ./scripts/**/*.sh

      - name: (BE) Setup DFX identity
        run: |
          dfx identity new github-ci --disable-encryption || true
          dfx identity use github-ci

      - name: (BE/FE) Deploy
        run: ./scripts/deploy.sh

      - name: (BE) Lint - Clippy
        run: |
          cd src/pt_backend && cargo clippy -- -D warnings
          cd ../shared && cargo clippy -- -D warnings

      - name: (FE) Format - Prettier
        working-directory: ./src/pt_frontend
        run: npm run format:write

      - name: (FE) TypeCheck - tsc
        working-directory: ./src/pt_frontend
        run: npm run typecheck

      - name: (FE) Lint - Biome/ESlint
        working-directory: ./src/pt_frontend
        run: npm run lint
